'use client'

import { motion } from 'framer-motion'
import {
  ExternalLink,
  Github,
  Utensils,
  FileText,
  Bot,
  Sparkles,
  TrendingUp,
  BarChart3,
} from 'lucide-react'
import { RevealOnScroll } from '@/components/animations/RevealOnScroll'

const featuredProject = {
  title: 'MyFoodTracker',
  tagline: 'Full-Stack AI Health Platform | Zero to Production in 6 Weeks',
  description:
    'What started as a personal challenge to track nutrition became a full-fledged AI health platform. I built every layer: a React frontend with real-time updates, a Node.js backend handling thousands of API calls, and custom ML models that recognize food from photos. The hardest part? Making it feel instant. I optimized the vision pipeline to return results in under 2 seconds.',
  icon: Utensils,
  highlights: [
    'Trained custom TensorFlow model on 100K+ food images, achieves 89% accuracy on real-world photos, handles edge cases like mixed plates',
    'Built personalized recommendation engine using collaborative filtering, suggests meals based on goals, preferences, and eating patterns',
    'Designed interactive D3.js dashboards with drill-down analytics, users track macros, trends, and progress over time',
    'Production-hardened with CI/CD, Docker containers, and cloud auto-scaling, handles traffic spikes without breaking a sweat',
  ],
  technologies: [
    'TypeScript',
    'React',
    'Node.js',
    'TensorFlow',
    'D3.js',
    'Docker',
  ],
  links: {
    live: 'https://my-food-tracker.com',
    github: 'https://github.com/yenugah80/mftweb',
  },
  color: 'primary',
}

const projects = [
  {
    title: 'Bias-Aware Hiring ML',
    subtitle: 'Published Research | IBAC 2025',
    description:
      'Tackled a real problem: hiring algorithms often perpetuate bias. I built ensemble models (CatBoost + XGBoost) that achieve 97% accuracy while reducing demographic bias by 40%. The key insight? Using SHAP explainability to identify and mitigate biased features without sacrificing predictive power. Paper accepted at IBAC 2025.',
    icon: TrendingUp,
    technologies: ['Python', 'CatBoost', 'XGBoost', 'SHAP', 'Fairlearn'],
    link: 'https://github.com/yenugah80/Revolutionizing-Recruitment-Enhanced-Machine-Learning-Models-for-Bias-Mitigation-and-Efficiency',
    color: 'secondary',
  },
  {
    title: 'Mermaid Maker',
    subtitle: 'LLM-Powered Diagram Generator',
    description:
      'Tired of manually writing diagram code? I built an AI that does it for you. Describe what you want in plain English, get production-ready Mermaid diagrams in seconds. Features live preview, version history, and one-click export. Over 500 diagrams generated by users so far, and counting.',
    icon: Sparkles,
    technologies: ['TypeScript', 'GPT-4', 'Mermaid.js', 'React'],
    link: 'https://github.com/yenugah80/Mermaid-Maker',
    color: 'accent',
  },
  {
    title: 'Enterprise Multi-Agent System',
    subtitle: 'Production LangGraph Architecture',
    description:
      'Built what I wish existed at work: autonomous AI agents that actually get things done. Using LangGraph for orchestration, these agents decompose complex tasks, pick the right tools, generate SQL queries, and self-correct when things go wrong. Now running in production, handling real business workflows.',
    icon: Bot,
    technologies: ['LangGraph', 'LangChain', 'FastAPI', 'Bedrock', 'Python'],
    link: 'https://github.com/yenugah80',
    color: 'primary',
  },
  {
    title: 'Executive Analytics Suite',
    subtitle: 'C-Suite Decision Intelligence',
    description:
      'Executives needed answers in minutes, not days. I built interactive Tableau and Power BI dashboards backed by real-time data pipelines, tracking $B+ in KPIs with drill-down capabilities. What used to take analysts days now happens automatically, refreshed every 15 minutes.',
    icon: BarChart3,
    technologies: ['Tableau', 'Power BI', 'SQL', 'Python', 'Airflow'],
    link: 'https://github.com/yenugah80/AnalyticsDashboardData',
    color: 'secondary',
  },
]

export function Projects() {
  return (
    <section id="projects" className="section relative overflow-hidden">
      <div className="container-custom mx-auto">
        <RevealOnScroll>
          <div className="text-center mb-16">
            <span className="badge-accent mb-4 inline-block">Side Projects & Research</span>
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-6">
              Built on <span className="gradient-text">Weekends</span>,
              <br className="hidden md:block" />
              <span className="text-foreground">Runs in Production</span>
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              The best way to learn is to build. From published research to apps people actually use,
              here&apos;s what happens when curiosity meets code.
            </p>
          </div>
        </RevealOnScroll>

        {/* Featured Project */}
        <RevealOnScroll>
          <motion.div
            className="glass rounded-3xl p-8 md:p-12 mb-12 gradient-border group"
            whileHover={{ y: -5 }}
          >
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div>
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-16 h-16 rounded-2xl bg-primary/10 border border-primary/30 flex items-center justify-center group-hover:glow transition-all duration-300">
                    <featuredProject.icon className="w-8 h-8 text-primary" />
                  </div>
                  <div>
                    <span className="badge mb-1">Featured Project</span>
                    <h3 className="text-2xl font-bold">{featuredProject.title}</h3>
                  </div>
                </div>
                <p className="text-lg text-primary font-medium mb-4">
                  {featuredProject.tagline}
                </p>
                <p className="text-muted-foreground mb-6">
                  {featuredProject.description}
                </p>
                <div className="flex flex-wrap gap-3 mb-6">
                  {featuredProject.technologies.map((tech, i) => (
                    <span key={i} className="badge">
                      {tech}
                    </span>
                  ))}
                </div>
                <div className="flex gap-4">
                  <motion.a
                    href={featuredProject.links.live}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="btn-primary flex items-center gap-2"
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                  >
                    <ExternalLink size={18} />
                    Live Demo
                  </motion.a>
                  <motion.a
                    href={featuredProject.links.github}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="btn-outline flex items-center gap-2"
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                  >
                    <Github size={18} />
                    GitHub
                  </motion.a>
                </div>
              </div>
              <div className="space-y-4">
                <h4 className="text-lg font-semibold mb-4">Key Achievements</h4>
                {featuredProject.highlights.map((highlight, i) => (
                  <div
                    key={i}
                    className="flex items-start gap-3 p-4 rounded-xl bg-primary/5 border border-primary/10"
                  >
                    <span className="text-primary text-lg">✓</span>
                    <span className="text-sm">{highlight}</span>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        </RevealOnScroll>

        {/* Other Projects */}
        <div className="grid md:grid-cols-2 gap-6">
          {projects.map((project, index) => (
            <RevealOnScroll key={index} delay={index * 0.1}>
              <motion.a
                href={project.link}
                target="_blank"
                rel="noopener noreferrer"
                className="glass rounded-2xl p-6 h-full hover-card group block card-shine inner-light"
                whileHover={{ y: -8, scale: 1.02 }}
                transition={{ type: 'spring', stiffness: 300, damping: 20 }}
              >
                <div className="flex items-start gap-4 mb-4">
                  <motion.div
                    className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0 group-hover:glow transition-all duration-500"
                    style={{
                      background: `hsl(var(--${project.color}) / 0.1)`,
                      borderWidth: '1px',
                      borderColor: `hsl(var(--${project.color}) / 0.3)`,
                    }}
                    whileHover={{ rotate: 5, scale: 1.1 }}
                  >
                    <project.icon
                      className="w-6 h-6 transition-transform duration-300 group-hover:scale-110"
                      style={{ color: `hsl(var(--${project.color}))` }}
                    />
                  </motion.div>
                  <div>
                    <h3 className="text-lg font-bold group-hover:text-primary transition-colors">
                      {project.title}
                    </h3>
                    {'subtitle' in project && (
                      <p className="text-xs text-muted-foreground mt-0.5">{project.subtitle}</p>
                    )}
                  </div>
                </div>
                <p className="text-muted-foreground mb-4">{project.description}</p>
                <div className="flex flex-wrap gap-2">
                  {project.technologies.map((tech, i) => (
                    <span
                      key={i}
                      className="badge text-xs"
                      style={{
                        background: `hsl(var(--${project.color}) / 0.1)`,
                        color: `hsl(var(--${project.color}))`,
                        borderColor: `hsl(var(--${project.color}) / 0.3)`,
                      }}
                    >
                      {tech}
                    </span>
                  ))}
                </div>
                <div className="mt-4 flex items-center gap-2 text-sm text-muted-foreground group-hover:text-primary transition-colors">
                  <Github size={16} />
                  <span>View on GitHub</span>
                  <ExternalLink size={14} className="ml-auto" />
                </div>
              </motion.a>
            </RevealOnScroll>
          ))}
        </div>

        {/* View All */}
        <RevealOnScroll>
          <div className="text-center mt-12">
            <motion.a
              href="https://github.com/yenugah80"
              target="_blank"
              rel="noopener noreferrer"
              className="btn-outline inline-flex items-center gap-2"
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
            >
              <Github size={18} />
              View All Projects on GitHub
            </motion.a>
          </div>
        </RevealOnScroll>
      </div>
    </section>
  )
}
